<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="QuanLySanPham.aspx.cs" Inherits="BTL.Quanlysanpham" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Quản lý sản phẩm</title>
    <style>
        ul {
            list-style: none;
        }

        li {
            display: inline;
            margin-right: 20px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <ul>
            <li><a href="Trangchu.aspx">Trang chủ</a></li>
            <li><a href="DanhSachSanPham.aspx">Danh sách sản phẩm</a></li>
            <li><a href="GioHang.aspx">Giỏ hàng</a></li>
            <li><a href="ThanhVien.aspx">Trang thành viên</a></li>
            <li><a href="BaoCaoThongKe.aspx">Báo cáo thống kê</a></li>
            <li><a href="QuanLySanPham.aspx">Quản lý danh sách sản phẩm</a></li>
        </ul>
        <asp:TextBox ID="txtTen" runat="server" placeholder="Tên SP"></asp:TextBox>
        <asp:TextBox ID="txtHang" runat="server" placeholder="Hãng"></asp:TextBox>
        <asp:TextBox ID="txtLoai" runat="server" placeholder="Loại"></asp:TextBox>
        <asp:TextBox ID="txtGia" runat="server" placeholder="Giá"></asp:TextBox>
        <asp:FileUpload ID="fanh" runat="server" />
        <asp:Button ID="btnThem" runat="server" Text="Thêm" OnClick="btnThem_Click" />
        <asp:Repeater ID="rptSanPham" runat="server">
            <ItemTemplate>
                <a href='ChiTietSanPham.aspx?id=<%# Eval("MaSP") %>' style="text-decoration: none; color: inherit;">
                    <div style="border:1px solid #ccc; margin:10px; padding:10px; border-radius: 8px;">
                        <h3><%# Eval("TenSP") %></h3>
                        <p>Hãng: <%# Eval("Hang") %> - Loại: <%# Eval("Loai") %></p>
                        <p>Giá: <%# String.Format("{0:N0}", Eval("Gia")) %> VNĐ</p>
                
                        <span style="color: blue; font-weight: bold;">Xem chi tiết >></span>
                    </div>
                </a>
            </ItemTemplate>
        </asp:Repeater>
        <asp:GridView ID="gvSanPham" runat="server" DataKeyNames="MaSP" OnRowDeleting="gvSanPham_RowDeleting" AutoGenerateDeleteButton="true">
        </asp:GridView>
    </form>
</body>
</html>
